#!/bin/bash
# Альтернативный план загрузки файлов если git не работает

echo "🔄 АЛЬТЕРНАТИВНЫЙ ПЛАН ЗАГРУЗКИ"
echo "==============================="
echo ""
echo "Если git pull не работает, используйте один из способов:"
echo ""

echo "СПОСОБ 1 - Прямое скачивание через wget:"
echo "========================================"
echo "cd /var/www/html  # или другая директория сайта"
echo ""
echo "# Скачивание основных дашбордов"
echo "wget -O inventory_products_dashboard.html 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/inventory_products_dashboard.html'"
echo "wget -O warehouse_dashboard.html 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/warehouse_dashboard.html'"
echo "wget -O warehouse_dashboard_advanced.html 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/warehouse_dashboard_advanced.html'"
echo ""
echo "# Скачивание CSS и JS"
echo "wget -O dashboard_styles.css 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/dashboard_styles.css'"
echo "wget -O inventory_products_script.js 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/inventory_products_script.js'"
echo "wget -O dashboard_script.js 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/dashboard_script.js'"
echo ""
echo "# Скачивание PHP файлов"
echo "wget -O warehouse_dashboard_api.php 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/warehouse_dashboard_api.php'"
echo "wget -O analyze_inventory_structure.php 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/analyze_inventory_structure.php'"
echo "wget -O analyze_sales_data_structure.php 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/analyze_sales_data_structure.php'"
echo "wget -O critical_warehouses_analysis.php 'https://raw.githubusercontent.com/Arbitr3103/mi_core_etl/main/critical_warehouses_analysis.php'"
echo ""
echo "# Установка прав"
echo "chmod 644 *.html *.css *.js *.php"
echo ""

echo "СПОСОБ 2 - Создание файлов через nano/vi:"
echo "========================================="
echo "Если wget не работает, создайте файлы вручную:"
echo "nano inventory_products_dashboard.html"
echo "# Скопируйте содержимое из локального файла"
echo ""

echo "СПОСОБ 3 - Загрузка через SCP:"
echo "==============================="
echo "С локальной машины выполните:"
echo "scp inventory_products_dashboard.html vladimir@178.72.129.61:/var/www/html/"
echo "scp warehouse_dashboard*.html vladimir@178.72.129.61:/var/www/html/"
echo "scp analyze_*.php vladimir@178.72.129.61:/var/www/html/"
echo "scp critical_*.php vladimir@178.72.129.61:/var/www/html/"
echo ""

echo "✅ ВЫБЕРИТЕ НАИБОЛЕЕ ПОДХОДЯЩИЙ СПОСОБ"