#!/bin/bash
# Команды для выполнения на сервере market-mi.ru

echo "🚀 КОМАНДЫ ДЛЯ СИНХРОНИЗАЦИИ ФАЙЛОВ НА СЕРВЕРЕ"
echo "=============================================="
echo ""
echo "1. Подключение к серверу:"
echo "ssh your-user@market-mi.ru"
echo ""
echo "2. Поиск директории с API (который работает):"
echo "find /var/www -name 'inventory-analytics.php' 2>/dev/null"
echo "find /home -name 'inventory-analytics.php' 2>/dev/null"
echo "find /usr/share/nginx -name 'inventory-analytics.php' 2>/dev/null"
echo ""
echo "3. Переход в найденную директорию:"
echo "cd /path/to/found/directory"
echo ""
echo "4. Проверка статуса git:"
echo "git status"
echo "git log --oneline -3"
echo ""
echo "5. Получение обновлений:"
echo "git pull origin main"
echo ""
echo "6. Проверка что файлы появились:"
echo "ls -la inventory_products_dashboard.html"
echo "ls -la warehouse_dashboard*.html"
echo "ls -la analyze_*.php"
echo "ls -la critical_*.php"
echo ""
echo "7. Установка прав доступа:"
echo "chmod 644 *.html *.css *.js *.php"
echo ""
echo "8. Проверка в браузере:"
echo "https://www.market-mi.ru/inventory_products_dashboard.html"
echo "https://www.market-mi.ru/analyze_inventory_structure.php"
echo ""
echo "✅ После выполнения всех команд система будет работать!"